### ISSUE TITLE
Node-red crashes when using central list

### ISSUE THREAD

**Issue by johntrygve** [tyrrellsystems/node-red-contrib-simple-weekly-scheduler#24]
Node-red crashes every 10 minute when using central list. 
Log:

24 Aug 21:17:29 - [red] Uncaught Exception:
24 Aug 21:17:29 - ReferenceError: response is not defined
at Request._callback (/home/pi/.node-red/node_modules/node-red-contrib-simple-weekly-scheduler/time-planner.js:36:33)
at Request.self.callback (/home/pi/.node-red/node_modules/request/request.js:188:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1171:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1091:12)
at IncomingMessage.g (events.js:292:16)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....

**Comment by hardillb** [comment]
I did mention it wasn't really ever tested....
